# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [13]:
import numpy as np

In [30]:
a = np.arange(15).reshape(3, 5)
print(a)
print('\n')
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


<class 'numpy.ndarray'>


In [37]:
print('list(a) ', list(a))  # list() - 只能轉換一層array

list(a)  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]


In [38]:
test = np.array([1, 2, 3, 4, 5])
list(test)

[1, 2, 3, 4, 5]

In [39]:
print('tolist(): ', a.tolist())  # tolist() - 可以多層轉換

tolist():  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [41]:
import numpy as np

In [46]:
a = np.random.randint(10, size=6) 
a

array([3, 5, 5, 0, 6, 4])

In [55]:
print(a.ndim)      # 陣列的維度
print(a.shape)     # 陣列的行列數
print(a.size)      # 陣列中有幾個元素
print(a.dtype)     # 陣列中的資料型態
print(a.itemsize)  # 陣列中每個元素佔用的空間
print(len(a))      # 陣列的長度
print(type(a))     # 類型：陣列
print(a.data)      # 陣列所存在的記憶體位置

1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [49]:
b = np.random.randint(10, size=(3,4)) 
b

array([[5, 0, 1, 0],
       [6, 4, 8, 5],
       [0, 3, 5, 1]])

In [57]:
print(b.ndim)      # 陣列的維度
print(b.shape)     # 陣列的行列數
print(b.size)      # 陣列中有幾個元素
print(b.dtype)     # 陣列中的資料型態
print(b.itemsize)  # 陣列中每個元素佔用的空間
print(len(b))      # 陣列的長度
print(type(b))     # 類型：陣列
print(b.data)      # 陣列所存在的記憶體位置

2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [50]:
c = np.random.randint(10, size=(2,3,2)) 
c

array([[[1, 8],
        [5, 7],
        [4, 4]],

       [[1, 3],
        [6, 2],
        [6, 7]]])

In [58]:
print(c.ndim)      # 陣列的維度
print(c.shape)     # 陣列的行列數
print(c.size)      # 陣列中有幾個元素
print(c.dtype)     # 陣列中的資料型態
print(c.itemsize)  # 陣列中每個元素佔用的空間
print(len(c))      # 陣列的長度
print(type(c))     # 類型：陣列
print(c.data)      # 陣列所存在的記憶體位置

3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [59]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))

[0, 1, 0, 6, 2, 0]
[0, 1, 0, 6, 2, 0]


In [60]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))

[[8, 0, 1, 6], [1, 0, 9, 1], [8, 2, 9, 9]]
[array([8, 0, 1, 6]), array([1, 0, 9, 1]), array([8, 2, 9, 9])]


In [85]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[8, 1], [3, 6], [1, 5]], [[2, 2], [5, 5], [1, 6]]]
[array([[8, 1],
       [3, 6],
       [1, 5]]), array([[2, 2],
       [5, 5],
       [1, 6]])]


In [86]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    newlist = []
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 1, 0, 6, 2, 0]
[[8, 0, 1, 6], [1, 0, 9, 1], [8, 2, 9, 9]]
[[[8, 1], [3, 6], [1, 5]], [[2, 2], [5, 5], [1, 6]]]
